version: '3'
services:
  web:
    build: .
    command: ./docker_setup_script
    volumes:
      - .:/transmitata
      - .root_home:/root
    restart: unless-stopped
    ports:
      - "8218:8000"
#      - "443:443"
