#!/bin/sh

ISARM=$(lscpu | grep arm)
cd /transmitata
pip install --upgrade pip
pip install -r requirements.txt --upgrade

if [ "$ISARM" = "Architecture:                    armv7l" ];
then
  echo 'Running loophole on ARM'
  python loophole_server.py &
  echo 'Running python server'
  python manage.py runserver 0.0.0.0:8000
else
  echo 'Development mode detected...'
fi

while [ 1 ]; do
    date
    sleep 30
done
