# Generated by Django 4.1.2 on 2026-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
